on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run build
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SFTP_HOST }}
        port: 22
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        protocol: ftps
        local-dir: ./dist/
        log-level: verbose
        server-dir: thegooble/
